#!/usr/bin/env bash
# Redirect nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '50i\rewrite ^/redirect_me http://dev-steph.tech permanent;' /etc/nginx/sites-available/default
sudo service nginx start
