#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

sudo apt-get -y install haproxy
sudo service haproxy start

sudo sed -i -e '$a\\nfrontend web-frontend\n\tbind :80\n\tdefault_backend web-backend' /etc/haproxy/haproxy.cfg
sudo sed -i -e '$a\\nbackend web-backend\n\tbalance roundrobin\n\tserver 271455-web-01 54.144.128.232:80 check\n\tserver 271455-web-02 18.204.20.190:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\nENABLED=1' /etc/default/haproxy
sudo service haproxy restart
