#!/usr/bin/env bash
# Displays its own process ID.

script="/var/run/myscript.pid"
echo $$ > "$script"
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo I hate the kill command && rm $script && exit' SIGTERM
	trap 'rm $script && exit' SIGQUIT
	trap "echo Y U no love me?!" SIGINT
done
