#!/usr/bin/env bash
# Displays lines containing the word bash.

for pid in /proc/[0-9]*/
do
	cmd="${pid}cmdline"
	pid=${pid%*/}
	pid=${pid##*/}
	echo -n "${pid} "
	if grep -q "bash" $cmd
	then
		cat $cmd
	fi
	echo
done
