#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hour=1
while ((hour<13))
do
	minute=1

	while ((minute<60))
	do
		echo "$minute"
		if [ $minute -eq 59 ]
		then
			echo "Hour: $hour"
		fi
		((minute++))
	done
	((hour++))
done
