#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hour=0
while ((hour<13))
do
	minute=1

	echo "Hour: $hour"
	while ((minute<60))
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
