#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01

sudo apt install ufw
echo "y" | sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw reload
